{% set name = "Professor" %}
{% set version = "2.5.1" %}
{% set tag = name|lower ~ "-" ~ version %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://gitlab.com/hepcedar/professor/-/archive/{{ tag }}/professor-{{ tag }}.tar.gz
  sha256: c49174d1e4117da13083928a57e9bd6a52be25b9ccadee620315742f8e6b9430
  patches:
    - 0001-Fix-LC_ID_DYLIB-on-macOS.patch

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - make
  host:
    - python
    - cython
    - pip
    - eigen
    - numpy
  run:
    - python
    - emcee
    - h5py
    - iminuit
    - ipython
    - matplotlib-base
    - numpy
    - pydoe
    - pymultinest
    - scikit-learn
    - scipy
    - sympy
    - tabulate
    - wxpython
    - yoda

test:
  imports:
    - professor2
  commands:
    - prof2-bootstrap --help
    - prof2-config --help
    - prof2-eigentunes --help
    - prof2-envelopes --help
    - prof2-errors --help
    - prof2-I --help
    - prof2-ipol --help
    - prof2-jackknife --help
    - prof2-ls --help
    - prof2-ncoeffs --help
    - prof2-plotspace --help
    - prof2-predict --help
    - prof2-residuals --help
    - prof2-runcombs --help
    - prof2-sample --help
    - prof2-sens --help
    - prof2-tune --help
    - prof2-tune-nest --help

about:
  home: https://professor.hepforge.org
  summary: A tuning tool for Monte Carlo event generators
  description: |
    Professor is a tuning tool for Monte Carlo event generators, based on the ideas
    described in "Tuning and Test of Fragmentation Models Based on Identified
    Particles and Precision Event Shape Data" (Z. Phys., C73 (1996) 11-60).
  license: GPL-3.0-only
  license_file: LICENSE
  doc_url: https://professor.hepforge.org/docs.sphinx220/index.html
  dev_url: https://gitlab.com/hepcedar/professor/

extra:
  recipe-maintainers:
    - admorris
